/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import {useEffect,useState} from "react";
import type{Film,MissingField}from"../src/domain/film";
import{compareLibraries}from"../src/domain/compare";
import{buildOfficialImports,buildSyncQueue}from"../src/domain/sync";
const icons:Record<string,React.ReactNode>={sync:<><path d="M20 7h-5V2"/><path d="M20 2l-4 4a7 7 0 1 0 2 9"/></>,history:<><path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5M12 7v5l3 2"/></>,settings:<><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1a1.7 1.7 0 0 0 1.9.3A1.7 1.7 0 0 0 10 3V2.8h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1Z"/></>,check:<path d="m5 12 4 4L19 6"/>,alert:<><path d="M12 9v4M12 17h.01"/><path d="M10.3 3.7 2.4 18a2 2 0 0 0 1.7 3h15.8a2 2 0 0 0 1.7-3L13.7 3.7a2 2 0 0 0-3.4 0Z"/></>,more:<><circle cx="5" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="19" cy="12" r="1" fill="currentColor"/></>,external:<><path d="M15 3h6v6M10 14 21 3"/><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/></>,chevron:<path d="m9 18 6-6-6-6"/>,user:<><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,phone:<><rect x="6" y="2" width="12" height="20" rx="2"/><path d="M11 18h2"/></>,close:<><path d="m6 6 12 12M18 6 6 18"/></>};
function Icon({name,size=22}:{name:string;size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden>{icons[name]}</svg>}

export default function Home(){
 const [screen,setScreen]=useState<"sync"|"history"|"settings">("sync"),[filter,setFilter]=useState<"ready"|"review"|"ignored">("ready");
 const [films,setFilms]=useState<Film[]>([]),[sc,setSc]=useState(""),[lb,setLb]=useState(""),[loading,setLoading]=useState(false),[lastSync,setLastSync]=useState<string|null>(null),[sheet,setSheet]=useState<Film|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState("");
 useEffect(()=>{const schema=localStorage.getItem("reviewonce-schema");if(schema!=="1"){["senssync-films","senssync-last","senssync-sc","senssync-lb"].forEach(key=>localStorage.removeItem(key));localStorage.setItem("reviewonce-schema","1");return}const f=localStorage.getItem("senssync-films"),l=localStorage.getItem("senssync-last"),a=localStorage.getItem("senssync-sc"),b=localStorage.getItem("senssync-lb");if(f)setFilms(JSON.parse(f));if(l)setLastSync(l);if(a)setSc(a);if(b)setLb(b)},[]);
 useEffect(()=>{if(films.length)localStorage.setItem("senssync-films",JSON.stringify(films))},[films]);
 const queue=buildSyncQueue(films),pending=queue.filter(item=>item.status!=="synced"),shown=films.filter(f=>filter==="ignored"?f.match==="ignored":f.match===filter);
 const count=(m:string)=>films.filter(f=>f.match===m).length;
 async function refresh(){if(!sc.trim()||!lb.trim()){setError("Renseigne tes deux noms de profil dans les réglages.");setScreen("settings");return}setLoading(true);setError("");setNotice("");try{const nonce=Date.now(),[sr,lr]=await Promise.all([fetch(`/api/senscritique?username=${encodeURIComponent(sc)}&refresh=1&_t=${nonce}`,{cache:"no-store"}),fetch(`/api/letterboxd?username=${encodeURIComponent(lb)}&_t=${nonce}`,{cache:"no-store"})]);const sd=await sr.json(),ld=await lr.json();if(!sr.ok)throw Error(sd.error||"SensCritique inaccessible");if(!lr.ok)throw Error(ld.error||"Letterboxd inaccessible");const scMovies:Film[]=ld.limited?sd.movies.filter((film:Film)=>film.watchedDate&&film.watchedDate>=ld.coverageFrom):sd.movies;setFilms(compareLibraries(scMovies,ld.movies,films,Boolean(ld.limited)));setNotice(ld.notice||"");const now=new Date().toISOString();setLastSync(now);localStorage.setItem("senssync-last",now);localStorage.setItem("senssync-sc",sc.trim());localStorage.setItem("senssync-lb",lb.trim())}catch(e){setError(e instanceof Error?e.message:"La comparaison a échoué")}finally{setLoading(false)}}
 function openAssist(f:Film){const target=f.letterboxdUrl||(f.tmdbId?`https://letterboxd.com/tmdb/${f.tmdbId}/`:`https://letterboxd.com/search/films/${encodeURIComponent(f.title)}/`);window.open(target,"_blank","noopener,noreferrer");setSheet(null)}
 function downloadCsv(name:string,content:string){const url=URL.createObjectURL(new Blob([content],{type:"text/csv;charset=utf-8"})),link=document.createElement("a");link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 async function prepareOfficialImport(selected=films){setLoading(true);setError("");try{const hydrated=[...selected];for(let index=0;index<hydrated.length;index++){const film=hydrated[index];if(film.match==="ready"&&film.missing?.includes("review")&&film.review==="present"&&film.reviewUrl){const response=await fetch(`/api/senscritique/review?path=${encodeURIComponent(film.reviewUrl)}`),data=await response.json();if(!response.ok)throw Error(data.error||`Critique inaccessible pour ${film.title}`);hydrated[index]={...film,review:data.review||""}}}const files=buildOfficialImports(hydrated);if(!files.diaryCount&&!files.watchlistCount)throw Error("Aucune entrée identifiée n’est prête à importer.");if(files.diary)downloadCsv("reviewonce-letterboxd-diary.csv",files.diary);if(files.watchlist)setTimeout(()=>downloadCsv("reviewonce-letterboxd-watchlist.csv",files.watchlist),250);setNotice(`${files.diaryCount} entrée${files.diaryCount>1?"s":""} et ${files.watchlistCount} ajout${files.watchlistCount>1?"s":""} watchlist préparés. Importe les fichiers sur Letterboxd puis relance la vérification.`);window.open("https://letterboxd.com/import/","_blank","noopener,noreferrer");setSheet(null)}catch(e){setError(e instanceof Error?e.message:"Préparation de l’import impossible")}finally{setLoading(false)}}
 function mark(f:Film,match:Film["match"]){setFilms(x=>x.map(i=>i.id===f.id?{...i,match,missing:match==="complete"?[]:i.missing}:i));setSheet(null)}
 function selectCandidate(f:Film,candidate:NonNullable<Film["matchCandidates"]>[number]){setFilms(items=>items.map(item=>item.id===f.id?{...item,tmdbId:candidate.tmdbId,letterboxdUrl:candidate.letterboxdUrl,matchCandidates:[],matchConfidence:candidate.confidence,match:"ready"}:item));setSheet(null)}
 const fieldLabel=(field:MissingField)=>({film:"Absent de Letterboxd",rating:"Note manquante sur Letterboxd",review:"Critique manquante sur Letterboxd",date:"Date manquante sur Letterboxd",watchlist:"Absent de la watchlist Letterboxd"}[field]);
 return <main className="app"><header className="appbar"><div className="appIdentity"><span className="logo">R</span><div><strong>ReviewOnce</strong><span>{lastSync?`Actualisé ${new Date(lastSync).toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"})}`:"Pas encore actualisé"}</span></div></div>{screen==="sync"&&<button className="iconButton" onClick={refresh} aria-label="Actualiser"><span className={loading?"spin":""}><Icon name="sync"/></span></button>}</header>
 <div className="content">
 {screen==="sync"&&<><section className="accountStrip"><div className="account sc"><span>SC</span><div><small>SensCritique</small><strong>{sc?`@${sc}`:"À renseigner"}</strong></div>{sc&&<i/>}</div><div className="linkLine"><span/><Icon name="sync" size={16}/><span/></div><div className="account lb"><span>LB</span><div><small>Letterboxd</small><strong>{lb?`@${lb}`:"À renseigner"}</strong></div>{lb&&<i/>}</div></section>
 <section className="syncSummary"><div><span className="bigCount">{pending.length}</span><div><h1>à compléter</h1><p>{pending.length?"Informations manquantes sur Letterboxd":"Lance une analyse pour vérifier les deux comptes"}</p></div></div><button onClick={refresh} disabled={loading}><Icon name="sync" size={18}/>{loading?"Analyse…":"Chercher les manques"}</button>{error&&<div className="syncError" role="alert"><Icon name="alert" size={17}/><span><strong>Comparaison impossible</strong>{error}</span></div>}{notice&&<div className="syncNotice"><Icon name="alert" size={17}/><span><strong>Information</strong>{notice}</span></div>}</section>
 <div className="segmented" role="tablist"><button aria-selected={filter==="ready"} onClick={()=>setFilter("ready")}>Prêts <span>{count("ready")}</span></button><button aria-selected={filter==="review"} onClick={()=>setFilter("review")}>À vérifier <span>{count("review")}</span></button><button aria-selected={filter==="ignored"} onClick={()=>setFilter("ignored")}>Ignorés <span>{count("ignored")}</span></button></div>
 <section className="list">{!films.length?<div className="emptyState"><div><Icon name="sync" size={28}/></div><h2>Cherche les informations manquantes</h2><p>L’application masque les films déjà complets et propose uniquement ce qui peut être ajouté à Letterboxd.</p><button onClick={refresh}>Analyser les deux comptes</button></div>:!shown.length?<div className="emptyState compact"><div><Icon name="check" size={28}/></div><h2>Rien dans cette vue</h2><p>{filter==="ready"?"Aucune information ne manque sur Letterboxd.":"Aucun film ne demande ton attention."}</p></div>:shown.map(f=><article className="film" key={f.id}><div className="poster">{f.poster?<img src={f.poster} alt=""/>:<span>{f.title[0]}</span>}</div><div className="filmMain"><h2>{f.title}</h2><p>{f.year}{f.watchedDate&&` · ${new Date(f.watchedDate+"T12:00").toLocaleDateString("fr-FR",{day:"numeric",month:"short"})}`}</p><div className="missingFields">{f.missing?.map(field=><span key={field}>{fieldLabel(field)}</span>)}</div><span className={`match ${f.match}`}><Icon name={f.match==="review"?"alert":"check"} size={13}/>{f.match==="review"?"Film à identifier":"Prêt à compléter"}</span></div><button className="more" onClick={()=>setSheet(f)} aria-label={`Actions pour ${f.title}`}><Icon name="more"/></button></article>)}</section>
 {count("ready")>0&&<div className="actionDock"><div><strong>{count("ready")} changement{count("ready")>1?"s":""}</strong><span>Import officiel · aucune ressaisie</span></div><button onClick={()=>prepareOfficialImport()} disabled={loading}>{loading?"Préparation…":"Tout préparer"} <Icon name="chevron" size={17}/></button></div>}</>}
 {screen==="history"&&<section className="screen"><div className="titleBlock"><h1>Activité</h1><p>Les entrées complétées ou déjà complètes.</p></div><div className="historyCard"><div className="historyIcon"><Icon name="check"/></div><div><strong>{count("complete")} entrées complètes</strong><span>Aucune information utile à ajouter</span></div></div>{films.filter(f=>f.match==="complete").map(f=><article className="historyRow" key={f.id}><span>{f.title[0]}</span><div><strong>{f.title}</strong><small>{f.year} · complet sur Letterboxd</small></div><Icon name="check" size={18}/></article>)}</section>}
 {screen==="settings"&&<section className="screen"><div className="titleBlock"><h1>Réglages</h1><p>Les noms de profil restent uniquement sur cet appareil.</p></div><h3 className="sectionLabel">COMPTES</h3><div className="settingsGroup"><label><span className="service sc">SC</span><div><small>SensCritique</small><input value={sc} placeholder="Nom de profil" autoComplete="off" spellCheck={false} onChange={e=>setSc(e.target.value)}/></div>{sc&&<i className="online"/>}</label><label><span className="service lb">LB</span><div><small>Letterboxd</small><input value={lb} placeholder="Nom de profil" autoComplete="off" spellCheck={false} onChange={e=>setLb(e.target.value)}/></div>{lb&&<i className="online"/>}</label></div>{error&&<div className="syncError" role="alert"><Icon name="alert" size={17}/><span><strong>Comptes requis</strong>{error}</span></div>}<h3 className="sectionLabel">SYNCHRONISATION</h3><div className="settingsGroup"><button><Icon name="external"/><div><strong>Import officiel en lot</strong><small>Notes, dates, critiques et watchlist sans ressaisie</small></div><span className="pill">Actuel</span></button><button className="disabled"><Icon name="sync"/><div><strong>Connexion Letterboxd officielle</strong><small>Synchronisation directe dès approbation OAuth/API</small></div><span className="pill soon">Demandée</span></button></div><div className="info"><Icon name="alert"/><p>ReviewOnce utilise l’import officiel aujourd’hui. La connexion OAuth remplacera les fichiers dès que Letterboxd accordera l’accès, sans conserver ton mot de passe.</p></div></section>}
 </div>
 <nav className="bottomNav" aria-label="Navigation principale"><button aria-current={screen==="sync"} onClick={()=>setScreen("sync")}><span><Icon name="sync"/>{pending.length>0&&<i>{pending.length}</i>}</span>À synchroniser</button><button aria-current={screen==="history"} onClick={()=>setScreen("history")}><Icon name="history"/>Activité</button><button aria-current={screen==="settings"} onClick={()=>setScreen("settings")}><Icon name="settings"/>Réglages</button></nav>
 {sheet&&<div className="scrim" onMouseDown={e=>e.currentTarget===e.target&&setSheet(null)}><section className="sheet"><div className="grab"/><button className="sheetClose" onClick={()=>setSheet(null)} aria-label="Fermer"><Icon name="close"/></button><div className="sheetFilm"><div className="poster large">{sheet.poster?<img src={sheet.poster} alt=""/>:sheet.title[0]}</div><div><h2>{sheet.title}</h2><p>{sheet.year} · {sheet.rating}/10 sur SensCritique</p></div></div>{sheet.matchCandidates?.length?<div className="candidateList"><small>QUEL EST LE BON FILM ?</small>{sheet.matchCandidates.map(candidate=><button key={candidate.tmdbId} onClick={()=>selectCandidate(sheet,candidate)}><span><strong>{candidate.title}</strong><em>{candidate.year||"Année inconnue"}</em></span><span>{candidate.confidence}%<Icon name="chevron" size={15}/></span></button>)}</div>:<><div className="sheetMissing"><small>À AJOUTER SUR LETTERBOXD</small>{sheet.missing?.map(field=><span key={field}><Icon name="check" size={14}/>{fieldLabel(field)}</span>)}</div><button className="mainAction" onClick={()=>prepareOfficialImport([sheet])}><Icon name="external"/>Préparer l’import officiel</button><p className="helper">La note, la date et la critique sont placées dans un fichier reconnu par Letterboxd. Aucune ressaisie.</p></>}<button className="secondaryAction" onClick={()=>openAssist(sheet)}><Icon name="external"/>Voir la fiche Letterboxd</button><button className="secondaryAction" onClick={()=>mark(sheet,"complete")}><Icon name="check"/>C’est maintenant complet</button><button className="textAction" onClick={()=>mark(sheet,"ignored")}>Ignorer cette entrée</button></section></div>}
 </main>
}
